apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-example
data:
  dbhost: 35.240.155.100
  application.properties: |-
    myconfig.properties1=Config 1 Updated
    myconfig.properties2=Config 2
    myconfig.subconfig1.properties1=Sub config 1 property 1
    myconfig.subconfig1.properties2=Sub config 1 property 2
    myconfig.subconfig2.properties1=Sub config 2 property 1
    myconfig.subconfig2.properties2=Sub config 2 property 2
    spring.datasource.url=jdbc:mysql://localhost:30306/mail
    ----
    spring.profile=kubernetes
    myconfig.properties1=Config 1 from kubernetes
    spring.datasource.url=jdbc:mysql://kubernetes:30306/mail
    myconfig.properties2=Config 4
    myconfig.subconfig1.properties1=Sub config 3 property 1
    myconfig.subconfig1.properties2=Sub config 3 property 2
    myconfig.subconfig2.properties1=Sub config 4 property 1
    myconfig.subconfig2.properties2=Sub config 4 property 2
